### ISSUE TITLE
folders

### ISSUE THREAD

**Issue by sentix001** [50t0r25/achievement-watchdog#1]
how to add multiple folders?

**Comment by 50t0r25** [comment]
If you're referring to game folders, it's currently not possible but i'm working on it and will update soon.

**Comment by 50t0r25** [comment]
Done, check the [latest release](https://github.com/50t0r25/achievement-watchdog/releases), i haven't tested it thoroughly but it should work fine, if you encounter any problems with it, reopen the issue.
