### ISSUE TITLE
Error when no games found

### ISSUE THREAD

**Issue by M4RCK5** [50t0r25/achievement-watchdog#3]
![image](https://github.com/user-attachments/assets/328cd608-589e-4b3f-b73d-adef68c04350)

Can we have the option to compile trough github actions??
That way others can make changes to it.

Can u remove the line 66?? that way i can integrate it in a batch file without it clearing the previous output.

**Comment by 50t0r25** [comment]
if i understand you correctly, the error is simply the unhandled exception, it doesn't have problems finding games right?? (assuming you have goldberg set up correctly in a game and have already unlocked one achievement, check `%appdata%\GSE saves\` to make sure a folder with the given game's ID is there if it's the case)

Other than that, i can't really replicate this unhandled exception, but i'm guessing that using sys.exit() instead of exit() should fix it, it would still be helpful to see what exactly you're doing in that batch file.

And yes, i'll remove screen clearing and see what i can do with GitHub actions.

**Comment by M4RCK5** [comment]
> if i understand you correctly, the error is simply the unhandled exception, it doesn't have problems finding games right?? (assuming you have goldberg set up correctly in a game and have already unlocked one achievement, check `%appdata%\GSE saves\` to make sure a folder with the given game's ID is there if it's the case)
> 
> Other than that, i can't really replicate this unhandled exception, but i'm guessing that using sys.exit() instead of exit() should fix it, it would still be helpful to see what exactly you're doing in that batch file.
> 
> And yes, i'll remove screen clearing and see what i can do with GitHub actions.

This is my batch script nothing fancy, it only reads the language from "steam_settings\settings\configs.user.ini" because im using "local_save_path=steam_settings" to make the "game + emu + steam saves" portable.

```
@echo off
title Achivement Viewer
cd /d "%~dp0"

for /f "tokens=2 delims=;=" %%a in ('findstr language settings\configs.user.ini 2^>nul') do set language=%%a

echo LOCAL_ACHIEVEMENTS_PATH=. >.env
echo GAMES_PATH=. >>.env
echo LANGUAGE=%language% >>.env

echo.
echo ----Achivment Viewer----
echo.

achievement-viewer.exe

echo.
pause
```

Im planning to add it to my set of scripts (EZLauncher.bat to be specific)
![image](https://github.com/user-attachments/assets/52493ee2-f412-4735-b433-67b88a2f34e8)

**Comment by 50t0r25** [comment]
That's really cool, i was initially planning to make it use the language from `configs.user.ini`, but most users might not be tech savvy and will probably not touch the config files, so to not add extra steps and have to look through `steam_settings` then `%appdata%\GSE saves\` and having to ask the user to change the language in these folders, i simply just added a language variable in the .env file.

Anyways, i'm working on adding the build workflow, never used it before so i'm kinda figuring it out, i should be done in not too long, and if you're ever going to publish your scripts, you can definitely bundle my tool with it, it looks really decent.

**Comment by M4RCK5** [comment]
> That's really cool, i was initially planning to make it use the language from `configs.user.ini`, but most users might not be tech savvy and will probably not touch the config files, so to not add extra steps and have to look through `steam_settings` then `%appdata%\GSE saves\` and having to ask the user to change the language in these folders, i simply just added a language variable in the .env file.
> 
> Anyways, i'm working on adding the build workflow, never used it before so i'm kinda figuring it out, i should be done in not too long, and if you're ever going to publish your scripts, you can definitely bundle my tool with it, it looks really decent.

Yeah i wrote the batch script because my launcher allows u to change the language between 3 (english/spanish/latam), i could add the other emu languages but i usually make repacks with only english and spanish languages bundled in, so in theory using that script will change the value in the ".env" file before execution.

Also i made EZLauncher because i use multiple steamclient_loader settings as multiple launch parametters so i had to make a dinamic menu that replaced the config file before launching the injection tool, after that i added lobby_connect to the script wich calls the injection tool and runs it with the launch parammetters to connect to mp lobbies without using the overlay, in the case of avatars/rundir/target/dlls u just need to drag and drop the files/folders inside the script window and it will retrieve the relative path, i tried to make everything easier trying to not exclude usefull options

**Comment by 50t0r25** [comment]
It took me a while to figure out how to get it to build correctly but i managed to somehow do it, check the [latest release](https://github.com/50t0r25/achievement-watchdog/releases), it should fix the screen clearing and unhandled exception, and you can also build a release through [Github actions](https://github.com/50t0r25/achievement-watchdog/actions/workflows/build.yml) now.

If your problems aren't fixed, feel free to reopen the issue.
