### ISSUE TITLE
Colourless Option for Achievement Viewer

### ISSUE THREAD

**Issue by M4RCK5** [50t0r25/achievement-watchdog#4]
Can we have a launch parametter for this?? as i was trying to integrate it into my batch script i had some troubles because each "fore white" kept overwrithing my batch script colour

(i removed the colours in a fork, i guess having it as a launch parametter could be usefull for other people too)

**Comment by 50t0r25** [comment]
Can you try just adding
```python
print(Style.RESET_ALL)
```
at the end of achievement_viewer.py and before each sys.exit() ? it should reset the terminal colors to how they were before the tool ran but i'm not sure, please test it on your fork, if it works i'll push it, if not i'll just add an argument to remove the colors.

**Comment by M4RCK5** [comment]
> Can you try just adding
> 
> ```python
> print(Style.RESET_ALL)
> ```
> 
> at the end of achievement_viewer.py and before each sys.exit() ? it should reset the terminal colors to how they were before the tool ran but i'm not sure, please test it on your fork, if it works i'll push it, if not i'll just add an argument to remove the colors.
> 
> Edit: also make sure you import Style from colorama
> 
> ```python
> from colorama import init, Fore, Style
> ```

I mean i dont want it to do change the text color back to white, in my launcher i use green as default text colour, i dont mind the other colours, in my fork i removed each fore command and the line 7 & 14 so the whole tool its using the colour i defined in the batch script atm.

**Comment by 50t0r25** [comment]
Just try it with this version here, it should just set back the terminal to whatever it was before (green in your case) if i'm not mistaken.
[Achievement_Viewer.zip](https://github.com/user-attachments/files/17512973/Achievement_Viewer.zip)

**Comment by M4RCK5** [comment]
> Just try it with this version here, it should just set back the terminal to whatever it was before (green in your case) if i'm not mistaken. [Achievement_Viewer.zip](https://github.com/user-attachments/files/17512973/Achievement_Viewer.zip)

Tried it and it doesnt work, it changes the text to white and stays like that after its execution ends.
I guess this doesnt work because to run it whitout changing the rundir of my script i need to use the command start /w /b wich runs the app without opening another window but it works as a second instance of cmd.exe with its own parametters

**Comment by 50t0r25** [comment]
Yeah then the documentation didn't really explain it well, anyways i just added a `-nocolor` argument to the latest release.

**Comment by M4RCK5** [comment]
@50t0r25
![image](https://github.com/user-attachments/assets/301ece2f-a7da-40de-8ca6-d1eb462debd3)

This "init(autoreset=True)" its what its changing the text colour even if "-nocolor" its used.
