### ISSUE TITLE
Unexpected UTF-8 BOM

### ISSUE THREAD

**Issue by reif22** [50t0r25/achievement-watchdog#8]
It appears using the latest goldberg emulator by Detanup01 while playing Ghost of Tsushima.
[achievement_watchdog.log](https://github.com/user-attachments/files/18266761/achievement_watchdog.log)

**Comment by 50t0r25** [comment]
I couldn't replicate this issue, it works fine on my side, could you please try extracting this archive directly inside the game's folder and try using it again: [Ghost of Tsushima.zip](https://github.com/user-attachments/files/18268044/Ghost.of.Tsushima.zip)

If this solves your issue, it means you just didn't generate the steam_settings folder currently, as the error on your logs says it couldn't parse the achievements file that you're supposed to generate.

**Comment by reif22** [comment]
Okey, I was using the repo GSE-Generator to get the achievements and generate steam_settings folder. After testing your .zip ,btw the .dll file didn't unlock achievements, instead the detanup01 latest .dll worked, so I used it instead of yours, and using generate_emu_config from detanup01 repo it worked. I will upload the achievements.json of both, I think they are the same (?), idk.
[achievements_GSEGenerator.json](https://github.com/user-attachments/files/18269779/achievements_GSEGenerator.json)

[achievements_generateEmuConfig.json](https://github.com/user-attachments/files/18269778/achievements_generateEmuConfig.json)

**Comment by 50t0r25** [comment]
I don't think the steam_settings folder generated by GSE-generator saves the achievements to the same path that's saved when the emulator is used by default, GSE-generator includes a bit too many settings by default that I don't think too many people should touch, that why i recommend using generate emu config.

Also, the .dll file i included is the latest (stable), I'm pretty sure your error was just a simple misconfiguration, make sure the paths in the .env file are all correct too.
